/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "6.2.9"

#define QTCHARTS_VERSION 0x060209

#endif // QT_QTCHARTS_VERSION_H
