/* This file was generated by syncqt. */
#ifndef QT_QTCHARTS_VERSION_H
#define QT_QTCHARTS_VERSION_H

#define QTCHARTS_VERSION_STR "6.2.12"

#define QTCHARTS_VERSION 0x06020C

#endif // QT_QTCHARTS_VERSION_H
